### ISSUE TITLE
OGC: Add paragraph about ModSpec in clause 4 (Terms)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#33]
From @ghobona

> Please add the following paragraph to the Terms and Definitions section as done in the [previous template](https://github.com/opengeospatial/templates/blob/master/standard_template/standard/clause_4_terms_and_definitions.adoc):
> 
> This document also uses terms defined in the OGC Standard for Modular Specifications ([OGC 08-131r3](https://portal.opengeospatial.org/files/?artifact_id=34762)), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

Originally from https://github.com/opengeospatial/ogc-metanorma-testing/issues/34

**Comment by ronaldtse** [comment]
@opoudjis isn't this part of the auto-gen text in clause 4?

**Comment by ghobona** [comment]
I got confused by the first paragraph which is not in the asciidoc content.

Adding the ModSpec text directly to the asciidoc content appears to work. So I am happy to close this issue.

![Screenshot 2020-10-26 at 07 28 56](https://user-images.githubusercontent.com/18121038/97144810-05b3d100-175d-11eb-80a6-e8b7c345e0b8.png)

**Comment by opoudjis** [comment]
> @opoudjis isn't this part of the auto-gen text in clause 4?

Currently no, only "For the purposes of this document,  the following terms and definitions apply" is (as an inherited Metanorma default), and any template text is appended to it.

I'm happy to handle this in auto-gen text instead of the template, but clearly there's a lack of clarity about which to use here. So, @ghobona, you say you're happy with where the document is at now, but:

1. Should we be ensuring that   "For the purposes of this document,  the following terms and definitions apply" *does not* appear in the output?
1. Is the ModSpec text to be entered for all OGC documents featuring terms & definitions, and not just Standards?

If the answer to either is "yes", then this becomes my issue, @manuel489.

**Comment by manuelfuenmayor** [comment]
Ping @ronaldtse to answer Nick questions and determine if this issue is a template matter.
Thanks!

**Comment by ronaldtse** [comment]
I think this is now done. Closing.
